# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: robot1_axis
  joint_model_group_pose: home_r1_axis
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - r1_cart_joint
    - r1_joint_1
    - r1_joint_2
    - r1_joint_3
    - r1_joint_4
    - r1_joint_5
    - r1_joint_6
    - r2_cart_joint
    - r2_joint_1
    - r2_joint_2
    - r2_joint_3
    - r2_joint_4
    - r2_joint_5
    - r2_joint_6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []